spring.application.name=sms

# MAMP MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/soldier_management_system
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver